FROM node:lts-alpine3.20

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY tsconfig.json ./

COPY src ./src

# Ensure the dist directory exists before running the build script
RUN mkdir -p dist

RUN npm run prebuild && npm run build

USER node

CMD ["npm", "start"]

EXPOSE 5050

