# Use the official Node.js 16 image
FROM node:lts-alpine3.20

# Set the working directory in the container
WORKDIR /app

# Copy the package.json file
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the code
COPY . .

# Set environment variables
ENV NODE_ENV development

# Run the command to start the development server
CMD ["npm", "run", "dev"]